openapi: 3.0.3
info:
  title: Interface API GUN2 – Opérateurs économiques
  description: Interface API exposée par GUN2 aux opérateurs économiques pour le dédouanement à l'exportation (Delta-IE)
  version: 1.0.0
  contact:
    name: DGDDI - Douane Française
    url: https://www.douane.gouv.fr/
tags:
  - name: Opérateurs vers DeltaIE
paths:
  /IE583:
    post:
      tags:
        - Opérateurs vers DeltaIE
      summary: Transmission d'information sur la sortie des marchandises ayant reçu la mainlevée pour exportation
      description: Transmission d'information sur la sortie des marchandises ayant reçu la mainlevée pour exportation
      operationId: messageIE583
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CC583BType"
      responses:
        "200":
          description: "Message envoyé avec succès"
        "400":
          description: "Erreur fonctionnelle sur les données nécessaires à la bonne prise en compte du message par la plateforme d'échange de l opérateur EDI : trame incomplète par exemple."
        "401":
          description: "Erreur d'authentification"
        "404":
          description: "URL inconnue."
        "500":
          description: "Erreur technique survenue ne permettant pas de prendre en compte la demande. L'erreur ne dépend pas du type de message."

components:
  schemas:
    CC583BType:
      type: object
      properties:
        messageSender:
          type: string
          description: Expéditeur
          maxLength: 35
          pattern: ^[a-zA-Z0-9]{1,35}
        messageRecipient:
          type: string
          description: Destinataire
          maxLength: 35
          pattern: ^[a-zA-Z0-9]{1,35}
        preparationDateAndTime:
          type: string
          description: Date et heure de préparation
          minLength: 19
          maxLength: 19
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}
        messageIdentification:
          type: string
          description: Identification du message
          maxLength: 35
          pattern: ^[a-zA-Z0-9]{1,35}
        messageType:
          type: string
          description: Type de message
          minLength: 6
          maxLength: 6
          pattern: ^[a-zA-Z0-9]{6}
        correlationIdentifier:
          type: string
          description: Identifiant de corrélation
          maxLength: 35
          pattern: ^[a-zA-Z0-9]{1,35}
        ExportOperation:
          $ref: "#/components/schemas/ExportOperationType"
        CustomsOfficeOfExport:
          $ref: "#/components/schemas/CustomsOfficeOfExportType"
        CustomsOfficeOfExitActualType:
          $ref: "#/components/schemas/CustomsOfficeOfExitActualType"
        Declarant:
          $ref: "#/components/schemas/MDeclarantType"
        Representative:
          $ref: "#/components/schemas/MRepresentativeType"
        ExitCarrier:
          $ref: "#/components/schemas/ExitCarrierType"
        AlternativeEvidence:
          type: array
          maxItems: 9
          items:
            $ref: "#/components/schemas/AlternativeEvidenceType"
      required:
        - messageSender
        - messageRecipient
        - preparationDateAndTime
        - messageIdentification
        - messageType
        - ExportOperation
        - CustomsOfficeOfExport
        - CustomsOfficeOfExit
        - Declarant

    SequenceNrContentType:
      type: number
      description: Numéro de séquence
      maxLength: 5
      pattern: ^[0-9]{1,5}

    IdentificationNumber:
      type: string
      description: Numéro d'identification
      maxLength: 17
      pattern: ^[a-zA-Z0-9]{1,17}

    MAddressType:
      type: object
      description: Adresse de l'exportateur
      properties:
        streetAndNumber:
          type: string
          description: Adresse / Numéro et rue
          maxLength: 70
          pattern: ^.{1,70}
        postcode:
          type: string
          description: Adresse / Code postal
          maxLength: 17
          pattern: ^.{1,17}
        city:
          type: string
          description: Adresse / Ville
          maxLength: 35
          pattern: ^.{1,35}
        country:
          type: string
          description: Adresse / Pays
          minLength: 2
          maxLength: 2
          pattern: ^[A-Z]{2}
      required:
        - streetAndNumber
        - city
        - country

    MContactPersonType:
      type: object
      description: Personne à contacter
      properties:
        name:
          type: string
          description: Personne à contacter / Nom
          maxLength: 70
          pattern: ^.{1,70}
        phoneNumber:
          type: string
          description: Personne à contacter / Numéro de téléphone
          maxLength: 35
          pattern: ^.{1,35}
        eMailAddress:
          type: string
          description: Personne à contacter / Adresse e-mail
          maxLength: 256
          pattern: ^[^@]+@[^\.]+\..+
      required:
        - name
        - phoneNumber

    #######################################################

    ExportOperationType:
      type: object
      description: Opération d'exportation
      properties:
        MRN:
          type: string
          description: MRN
          minLength: 18
          maxLength: 18
          pattern: ^[0-9]{2}[A-Z]{2}[A-Z0-9]{12}[A-E]{1}[0-9]
        exitDate:
          type: string
          description: Date de sortie
          minLength: 10
          maxLength: 10
          pattern: '^\d{4}-\d{2}-\d{2}$'
        enquiryInformationCode:
          type: number
          description: Code de procédure de recherche
          minimum: 0
          maximum: 9
      required:
        - MRN
        - enquiryInformationCode

    CustomsOfficeOfExportType:
      type: object
      description: Bureau de douane d'exportation
      properties:
        referenceNumber:
          type: string
          description: Bureau de douane d'exportation /  Code bureau
          minLength: 8
          maxLength: 8
          pattern: ^[A-Z]{2}[A-Z0-9]{8}
      required:
        - referenceNumber

    CustomsOfficeOfExitActualType:
      type: object
      description: Bureau de douane de sortie (effectif)
      properties:
        referenceNumber:
          type: string
          description: Bureau de douane de sortie (effectif) / Code bureau
          minLength: 8
          maxLength: 8
          pattern: ^[A-Z]{2}[A-Z0-9]{8}
      required:
        - referenceNumber

    MDeclarantType:
      type: object
      description: Déclarant
      properties:
        identificationNumber:
          $ref: "#/components/schemas/IdentificationNumber"
        name:
          type: string
          description: Déclarant / Nom
          maxLength: 70
          pattern: ^.{1,70}
        Address:
          $ref: "#/components/schemas/MAddressType"
        ContactPerson:
          $ref: "#/components/schemas/MContactPersonType"
      required:
        - ContactPerson

    MRepresentativeType:
      type: object
      description: Représentant
      properties:
        identificationNumber:
          $ref: "#/components/schemas/IdentificationNumber"
        status:
          type: string
          description: Représentant / Code du statut du représentant
          minLength: 1
          maxLength: 1
          pattern: ^[0-9]{1}
        ContactPerson:
          $ref: "#/components/schemas/MContactPersonType"
      required:
        - identificationNumber
        - status
        - ContactPerson

    ExitCarrierType:
      type: object
      description: Transporteur à la sortie
      properties:
        identificationNumber:
          $ref: "#/components/schemas/IdentificationNumber"
        name:
          type: string
          description: Transporteur  à la sortie / Nom
          maxLength: 70
          pattern: ^.{1,70}
        Address:
          $ref: "#/components/schemas/MAddressType"

    AlternativeEvidenceType:
      type: object
      description: Preuve alternative
      properties:
        sequenceNumber:
          $ref: "#/components/schemas/SequenceNrContentType"
        type:
          type: string
          description: Preuve alternative / Type
          minLength: 2
          maxLength: 2
          pattern: ^[0-9]{2}
        TransportDocument:
          type: array
          maxItems: 99
          items:
            $ref: "#/components/schemas/MTransportDocumentType"
      required:
        - sequenceNumber
        - type

    MTransportDocumentType:
      type: object
      description: Document de transport
      properties:
        sequenceNumber:
          $ref: "#/components/schemas/SequenceNrContentType"
        type:
          type: string
          description: Document de transport / Type
          minLength: 4
          maxLength: 4
          pattern: ^[a-zA-Z0-9]{4}
        referenceNumber:
          type: string
          description: Document de transport / Numéro de référence
          maxLength: 70
          pattern: ^.{1,70}
      required:
        - sequenceNumber
        - type
        - referenceNumber
